name: CI

# Kiểm soát khi nào dòng công việc sẽ chạy
on:
  # Kích hoạt quy trình làm việc trên các sự kiện yêu cầu đẩy hoặc kéo nhưng chỉ cho nhánh "main"
  push:
    branches: [ "main" ]

  # Cho phép bạn chạy quy trình công việc này theo cách thủ công từ tab Action
  # workflow_dispatch:

# Workflow chạy được tạo thành từ một hoặc nhiều công việc có thể chạy tuần tự hoặc song song
jobs:
  # Dòng công việc này chứa một công việc duy nhất được gọi là "build"
  build:
    # Nền tảng mà công việc sẽ chạy
    runs-on: windows-latest

    # Các bước thể hiện một chuỗi các nhiệm vụ sẽ được thực hiện như một phần của công việc
    steps:
      # Kiểm tra kho lưu trữ của bạn dưới $ GITHUB_WORKSPACE, để công việc của bạn có thể truy cập nó
      # - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Run Python
        run: python main.py